added lesson10 branch
Hita4i/beetroot pull request #7
Opened 2020-11-26 15:11 UTC by Hita4i

2020-11-26 15:49 UTC, podhornyi approved these changes

2020-12-16 10:34 UTC, podhornyi requested changes

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def __init__(self, valid_channel=CHANNELS[0]):
передавай сюда не канал, а список каналов
и определяй текущий (допустим по умолчанию при включении ТВ будет выбираться первый канал)

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[0]
`valid_channel` > `current_channel`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = valid_channel
`valid_channel` > `current_channel`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[0]
`current_channel = self.channels[0]`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[-1]
по аналогии с `switch_to_first_channel`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def switch_to_turn_channel(self):
`switch_to_turn_channel` > `switch_to_channel`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def switch_to_turn_channel(self):
и параметром передавай ИД канала, отталкиваясь от этого ИД уже переключай на него (если не выходит за рамки листа)

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def switch_to_next_channel(self):
увеличиваешь `current_channel` на 1
смотришь не вылезли ли мы за длину наших каналов (которые то сохранишь в init)
если нет - возвращаешь имя канала по ИД
еси да - вызови `self.switch_to_last_channel`

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def switch_to_previous_channel(self):
по аналогии с `switch_to_next_channel`, только в случае ошибки вернуть первый канал

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        return self.valid_channel
не то
верни текущее имя канала по его ИД

P.S. Спосок каналов ты сохраняешь в init, текущий ИД канала ты меняешь в методах которые переключат канал

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def is_exist(self):
передавай как параметр ИД канала

2020-12-16 10:34 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        for i in range(1, self.list_of_channel + 1):
этот код не рабочий - найди причину и расскажи почему
ты его запускал?

2020-12-16 11:44 UTC, Hita4i commented on lesson10/tvcontroller.py
> +        for i in range(1, self.list_of_channel + 1):
BBC
Ведите интересующий канал: 1
Yes
Ведите интересующий канал: BBC
Yes
Ведите интересующий канал: SSB
NO

Process finished with exit code 0

2020-12-16 17:20 UTC, Hita4i commented on lesson10/tvcontroller.py
> +    def __init__(self, valid_channel=CHANNELS[0]):
def __init__(self, valid_channel=CHANNELS):
        self.valid_channel = valid_channel[0]
вот так?

2020-12-16 18:39 UTC, Hita4i commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[0]
valid_channel изменить на  current_channel и current_channel = self.channels[0] ?
TVController.CHANNELS[0] вот так не использовать потому, что я список каналов передал в инит и теперь от него плясать ?

2020-12-16 20:24 UTC, podhornyi requested changes

2020-12-16 20:24 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        for i in range(1, self.list_of_channel + 1):
Точно, ошибся
показалось сначала что ты в `range` передаешь `exist_channel`

2020-12-16 20:24 UTC, podhornyi commented on lesson10/tvcontroller.py
> +    def __init__(self, valid_channel=CHANNELS[0]):
нет
1. Вынеси вообще `CHANNELS` из класса
2. `self.channels = channels[0]` прочитай этот код с учетом имен переменных и подумай что тут не так, что получается справа от знака равно и в какую переменную ты это что-то присваиваешь

2020-12-16 20:24 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[0]
valid_channel изменить на current_channel и current_channel = self.channels[0] ? - да только `self.current_channel`

2020-12-16 20:24 UTC, podhornyi commented on lesson10/tvcontroller.py
> +        self.valid_channel = TVController.CHANNELS[0]
TVController.CHANNELS[0] вот так не использовать потому, что я список каналов передал в инит и теперь от него плясать ? - именно

2021-01-03 19:42 UTC, podhornyi approved these changes

2021-01-06 11:09 UTC, merged